name: "Hello World workflow"

# Controls when the action wil run. Trrigers the workflow on push some to master or production branch.

on:
  push:
    branch:
      -master
      -production

jobs:
  hello_world:
    runs-on: ubuntu latest
    steps:
      - name: "Print Hello"
        run: echo "Hello"
        
