name: "Hello World workflow"

on:
  push:
    branch:
      -master
      -production

jobs:
  hello_world:
    runs-on: ubuntu latest
    steps:
      - name: "Print Hello"
        run: echo "Hello"
        
